### ISSUE TITLE
Аддон для Firefox

### ISSUE THREAD

**Issue by niceguy135** [BIG-Denis/dark-orioks#3]
Привет! Планируется ли выпуск расширения в качестве аддона для Firefox?

**Comment by BIG-Denis** [comment]
Добрый день!
Такая попытка уже была, на что firefox ответили, что из-за того, что данное расширение имеет ограниченную аудиторию (студенты НИУ МИЭТ), то данное расширение не может быть опубликовано в общественном магазине.
Это часть политики firefox, собственно, и магазин у них бесплатаный. У корпорации Google другой подход: отвалил им 5$ и можешь публиковать что угодно (не нарушающее правила конфиденциальности), другими словами "любой каприз за ваши деньги". Для пользователей firefox и других браузеров, где невозможна установка из магазина chrome web store предлагается скачать расширение zip-пакетом с github или gitlab и установить его вручную, используя режим разработчика.
В связи с вышеуказанными обстаятельствами, закрываем данную тему с пометкой о невозможности решения.
С уважением,
команда разработки Dark ORIOKS
